### ISSUE TITLE
Error thrown while running command "swiftmailer:spool:send -e=prod". Message: "Call to a member function has() on null"

### ISSUE THREAD

**Issue by axzx** [symfony/swiftmailer-bundle#218]
```
swiftmailer/swiftmailer                  v6.0.2
symfony/swiftmailer-bundle               v3.1.6
symfony/symfony                          v3.3.14
```

```
{
    "class": "Error",
    "message": "Call to a member function has() on null",
    "code": 0,
    "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:592",
    "trace": [
        "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php:146",
        "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:375",
        "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:174",
        "vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php:169",
        "vendor/symfony/swiftmailer-bundle/Command/SendEmailCommand.php:110",
        "vendor/symfony/swiftmailer-bundle/Command/SendEmailCommand.php:85",
        "vendor/symfony/swiftmailer-bundle/Command/SendEmailCommand.php:64",
        "vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:240",
        "vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:875",
        "vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:215",
        "vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:71",
        "vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122",
        "bin/console:28"
    ]
}
```

**Comment by jkobus** [comment]
@axzx Did you manage to solve this?

**Comment by axzx** [comment]
@jkobus I can't check it now

**Comment by salvatorecordiano** [comment]
Hi, I upgraded `swiftmailer-bundle` from `v5.4.9` to `v6.2.1`. When I run spool command, I'm experiencing the following issue:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function has() on null in /var/www/project/releases/project/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:581
Stack trace:
#0 /var/www/project/releases/project/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(146): Swift_Mime_SimpleMimeEntity->_getHeaderFieldModel('Return-Path')
#1 /var/www/project/releases/project/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(339): Swift_Mime_SimpleMessage->getReturnPath()
#2 /var/www/project/releases/project/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(161): Swift_Transport_AbstractSmtpTransport->_getReversePath(Object(Swift_Message))
#3 /var/www/project/releases/project/src/Worker/EmailSendWorker.php(213): Swift_Transport_A in /var/www/project/releases/project/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php on line 581
```

I'm using a custom spool on MongoDB with these packages:

```
"symfony/swiftmailer-bundle": "v3.2.6"
"swiftmailer/swiftmailer": "v6.2.1"
"symfony/symfony": "v3.4.22"
```

My issue is very similar this issue. 

@axzx how did you solve your issue?

**Comment by jkobus** [comment]
If I remember well, @salvatorecordiano, in my case it was an old email in spool directory. Removing it solved the issue.

**Comment by salvatorecordiano** [comment]
Ok @jkobus, in my case it's different. I started using an empty queue.
